version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - echo "Build started on $(date)"

      - echo Installing dependencies...
      - pip install -U pytest

      - echo Checking pytest version
      - pytest --version
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'